package com.example.demo1.UsersProfiles;

public enum Traits {
    SERIOUS, ORGANISED, TEAM_PLAYER, LAZY, GENEROUS, EARLY_RISER,
    CASUAL, RESPONSIBLE, SOFT, IRRESPONSIBLE, LEADER, HYPERACTIVE,
    SOLITARY, INDIFFERENT, SELFISH, CALM, PERFECTIONIST, ENTHUSIASTIC,
    OUTGOING, CAUTIOUS, EXTROVERT, INTROVERT, NIGHT_OWL, SPONTANEOUS,
    SOCIAL, SOBER

}
